server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
    properties:
      hibernate:
        format_sql: true



