server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/board
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data.rest:
    base-path: /api
    detection-strategy: annotated

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always



